### ISSUE TITLE
How do I add new modifiers to the csv file

### ISSUE THREAD

**Issue by dumbgoos** [gagneurlab/spectralis#1]
While we are eagerly interested in your research outcomes, we also have the intention to add new modifiers, such as "N(+.98) ": 115.026943; "Q(+.98) ": 129.042594; "Q (-17.03)" : 111.032029, to the aa_mass_lookup.csv file. However, there is uncertainty regarding the required format for modifiers in files like aa_mass_lookup.csv. We kindly request clarification on the process of integrating these modifiers into the file. Alternatively, could you furnish us with an aa_mass_lookup.csv file that already includes these specified modifiers?
Below are specific instances where the inclusion of modified amino acids is required.
```yaml
Fixed Modifications:
Carbamidomethylation: +57.021464
variable Modifications:
Deamidation (N/Q): +0.984016
Oxidation (M): +15.994915
Pyro-glu from Q: -17.026549
```
